version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          JAVA_OPTS: -XX:+UseG1GC
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

    working_directory: ~/build-working-directory
    steps:
      - checkout
      - run:
          command: |
            mkdir -p build
            find build.gradle.kts gradle buildSrc/src buildSrc/build.gradle.kts -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
          name: Generate cache key
      - restore_cache:
          keys:
            - v1-home-cache-{{ checksum "build/circle-ci-key.txt" }}
            - v1-home-cache-
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache-
      - run:
          command: |
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version
            javac -version
          name: Show Java Version
      - run:
          command: ./gradlew build --stacktrace --scan
          name: Gradle Build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-home-cache-{{ checksum "build/circle-ci-key.txt" }}
      - store_test_results:
          path: ~/build-working-directory/build/test-results/
      - save_cache:
          paths:
            - ~/build-working-directory/.gradle
            - ~/build-working-directory/build
            - ~/build-working-directory/buildSrc/.gradle
            - ~/build-working-directory/buildSrc/build
          key: v1-build-cache-{{ .Branch }}-{{ .BuildNum }}


